### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by HrishiDhondge** [DNAReplicationLab/DNAscentTools#1]
Hello @sathish-t, 

I am trying to use this repository for converting a `detect` file to `modBAM` format. I am using the same package versions as mentioned in the `requirement.txt` file. But when I run the `run_detect_to_modBAM.sh` script, I am getting the following error:
```
Traceback (most recent call last):
  File "/data/DNAscentTools/convert_detect_to_modBAM.py", line 68, in <module>
    convert_dnascent_detect_to_modBAM_file(
  File "/data/DNAscentTools/modBAM_tools.py", line 279, in convert_dnascent_detect_to_modBAM_file
    seg.set_tag("ML", list(fn_rev_if_needed(prob_frm0_to255)))
  File "pysam/libcalignedsegment.pyx", line 2338, in pysam.libcalignedsegment.AlignedSegment.set_tag
  File "pysam/libcalignedsegment.pyx", line 2471, in pysam.libcalignedsegment.AlignedSegment.set_tag
  File "pysam/libcalignedsegment.pyx", line 363, in pysam.libcalignedsegment.pack_tags
ValueError: min() arg is an empty sequence
```
Have you encountered this error before? Is there any solution or workaround for this? 
The `detect` file is from the DNAscent `Version 4.0.1`.

**Comment by sathish-t** [comment]
Hi,

I've updated the code base to deal with DNAscent v4. Can you give it a shot now? Thanks!

Regards
Sathish

**Comment by sathish-t** [comment]
Please consult the updated run_detect_to_modBAM.sh which shows how to run the code for different DNAscent versions.

**Comment by HrishiDhondge** [comment]
Thanks for the prompt action. I quickly checked and it seems to work. I'll investigate further in detail tomorrow.
